services:
  # Full Site Service (Static + CMS Admin)
  - type: web
    name: flegmit
    env: node
    buildCommand: npm install && npm run setup && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    disk:
      name: flegmit-db
      mountPath: /opt/render/project/src/database
      sizeGB: 1